export default {
  PLATE: require("../assets/plate.png"),
  DISCOVER: require("../assets/discover.png"),
  DELIVER: require("../assets/deliver.png"),
  FAVORITE: require("../assets/favorite.png"),
  FACEBOOK: require("../assets/facebook.png"),
  GOOGLE: require("../assets/google.png"),
  LOADING: require("../assets/loading.json"),
  FRIED_CHICKEN: require("../assets/fried_chicken.png"),
  BURGER: require("../assets/burger.png"),
  PIZZA: require("../assets/pizza.png"),
  DESSERT: require("../assets/dessert.png"),
  NOODLES: require("../assets/noodles.png"),
  DRINKS: require("../assets/drinks.png"),
  DELIVERY_TIME: require("../assets/delivery_time.png"),
  DELIVERY_CHARGE: require("../assets/delivery_charge.png"),
  MARKER: require("../assets/marker.png"),
  EMPTY_CART: require("../assets/empty_cart.png"),
  AVATAR: require("../assets/user_avatar.png"),
  SUCCESSIGNUP: require("../assets/undraw_welcome_cats_thqn.png"),
  RESSETPASSWORD: require("../assets/undraw_Mail_sent_re_0ofv.png"),
};
